### ISSUE TITLE
As a programming enthusiast, I had some problems deploying projects

### ISSUE THREAD

**Issue by Xinchenlove** [google/generative-ai-android#16]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\14130\AndroidStudioProjects\generative-ai-android\plugins\build.gradle.kts' line: 17

* What went wrong:
Plugin [id: 'org.gradle.kotlin.kotlin-dsl', version: '4.1.2'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:4.1.2')
  Searched in the following repositories:
    Google
    MavenRepo
    Gradle Central Plugin Repository

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'org.gradle.kotlin.kotlin-dsl', version: '4.1.2'] was not found in any of the following sources:

	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)

CONFIGURE FAILED in 27s

As a programming enthusiast, I had some problems deploying projects

**Comment by rlazo** [comment]
Hi @Xinchenlove thanks for your report. Could you provide more info on your set up?

What OS you are using?
What java version you are using?

Also, is this a clean clone of the repo?
