### ISSUE TITLE
kotlin version

### ISSUE THREAD

**Issue by abcwangxiang** [google/generative-ai-android#33]
implementation "com.google.ai.client.generativeai:generativeai:0.1.1"  appears incompatible version of Kotlin issue：Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.  But I cannot upgrade kotlin & gradle in my project.

**Comment by daymxn** [comment]
We should not be expecting version `1.9.0`; our intended version is `1.8.x`- which came out in December of 2022 (two years ago). This will be fixed with #34.

Unfortunately, `1.7.1` is too old for us to support; you will need to upgrade to `1.8.x` to take advantage of this SDK.
