### ISSUE TITLE
Request for Function Calling Feature

### ISSUE THREAD

**Issue by Bhuvaneshw** [google/generative-ai-android#40]
I'd like to propose the addition of a Function Calling feature to enhance communication between Android device and the model

**Comment by rlazo** [comment]
Hey @Bhuvaneshw, thanks for your proposal. Yes! function calling is a feature that's part of our roadmap. Stay tuned!

I'll keep the issue open until the feature is implemented to keep you in the loop.

**Comment by rlazo** [comment]
Hi @Bhuvaneshw our latest release supports function calling https://github.com/google/generative-ai-android/releases/tag/v0.3.0 thanks for your patience!
