### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by temdenes** [google/generative-ai-android#79]
A new official release because the current version does not yet contain the fix for the "API Error 400: please use a valid role: user, model error" #75 issue.

**Comment by Tolansoft** [comment]
I have same issue "Chat prompts should come from the 'user' role."

**Comment by temdenes** [comment]
> I have same issue "Chat prompts should come from the 'user' role."

It has already been resolved and approved, but the latest release does not include the fix yet

**Comment by Tolansoft** [comment]
Thank you 🙏

9 Mar 2024 Cmt 23:33 tarihinde Dénes Temleitner ***@***.***>
şunu yazdı:

**Comment by Unshd0012** [comment]
Hello,

I have encountered the same issue reported here, "Chat prompts should come from the 'user' role.", while working with version 0.2.1 of the library. The error arises when I try to send a message in my  function, despite ensuring that all messages in the chat history are assigned with the "user" role.

![image](https://github.com/google/generative-ai-android/assets/76157405/6f60f612-a068-4c9b-b324-0562a5c3aff7)

**Comment by temdenes** [comment]
> Hello,
> 
> I have encountered the same issue reported here, "Chat prompts should come from the 'user' role.", while working with version 0.2.1 of the library. The error arises when I try to send a message in my function, despite ensuring that all messages in the chat history are assigned with the "user" role.
> 
> ![image](https://private-user-images.githubusercontent.com/76157405/311488187-6f60f612-a068-4c9b-b324-0562a5c3aff7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNTkwMTEsIm5iZiI6MTcxMDA1ODcxMSwicGF0aCI6Ii83NjE1NzQwNS8zMTE0ODgxODctNmY2MGY2MTItYTA2OC00YzliLWIzMjQtMDU2MmE1YzNhZmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDA4MTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMzFhZGIzYTc1NWI0MWY0ZWMxNjc0NGMzODEyZWUwNGU2NThjODY1N2U3YTE5NGM0YTA4ZTc5ZDY1NTBiNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fEwry-OlfXSyKSOA2UVAgfRtPrpSHSxii0B9XDJ1j7Q)

Until a new version is released, I think version 0.2.0 is used, I use it too and it works perfectly.

**Comment by temdenes** [comment]
Thank you @rlazo

**Comment by rlazo** [comment]
You are welcomed @temdenes . The release is still being generated, though. I will close this issue once the artifacts are ready to download from Maven

**Comment by temdenes** [comment]
Thank you very much @rlazo

**Comment by rlazo** [comment]
And... it's out!

https://maven.google.com/web/index.html?q=generative#com.google.ai.client.generativeai:generativeai:0.2.2

Let us know if you find any issues. Thanks
